name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK (or your environment)
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run tests
        run: ./gradlew test

      - name: Create Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload build folder as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/
